#Requires -Version 5.0

param (
    [Parameter(Mandatory = $true, HelpMessage = "Enter the LaTeX filename without the .tex extension.")]
    [string]$FileName
)

$TexFile = "${FileName}.tex"

# --- Configuration ---
# Add or remove auxiliary file extensions as needed
$AuxFileExtensions = @(
    ".aux",
    ".log",
    ".toc", # Table of Contents
    ".lof", # List of Figures
    ".lot", # List of Tables
    ".out", # Hyperref outlines, etc.
    ".synctex.gz", # SyncTeX file for editor/PDF sync
    ".fls", # File list generated by some processes
    ".fdb_latexmk", # Latexmk database file
    # For BibTeX/Biber (uncomment if you use them)
    ".bbl",    # Bibliography file (BibTeX/Biber)
    ".blg"    # Bibliography log file (BibTeX/Biber)
    # ".bcf",    # Biber control file
    # ".run.xml" # Biber run file
)

# Number of XeLaTeX runs (usually 2-3 for references/TOC to stabilize)
# We now control the passes explicitly for biblatex workflow
$XeLaTeXRunsForBiblatex = 2 # Additional XeLaTeX runs after Biber

# --- Check if .tex file exists ---
if (-not (Test-Path -Path $TexFile -PathType Leaf)) {
    Write-Error "Error: LaTeX file '$TexFile' not found in the current directory."
    exit 1
}

# --- Compilation Steps for biblatex ---
Write-Host "Starting XeLaTeX compilation for '$TexFile'..."

# Pass 1: Run XeLaTeX to generate .aux file for Biber
Write-Host "Running XeLaTeX pass 1 (generating .aux for Biber)..."
xelatex.exe -interaction=nonstopmode -halt-on-error "$TexFile"
if ($LASTEXITCODE -ne 0) {
    Write-Error "XeLaTeX compilation failed on initial pass. Check '$FileName.log' for details."
    exit $LASTEXITCODE
}

# Run Biber to process citations and generate .bbl file
Write-Host "Running Biber..."
biber.exe "$FileName"
if ($LASTEXITCODE -ne 0) {
    Write-Error "Biber processing failed. Check '$FileName.blg' for details."
    # We exit here because if Biber fails, citations won't resolve anyway
    exit $LASTEXITCODE
}

# Subsequent Passes: Run XeLaTeX again to resolve citations and cross-references
for ($i = 1; $i -le $XeLaTeXRunsForBiblatex; $i++) {
    $currentPass = $i + 1 # Display pass number correctly (2, 3, etc.)
    Write-Host "Running XeLaTeX pass $($currentPass) (resolving references)..."
    xelatex.exe -interaction=nonstopmode -halt-on-error "$TexFile"
    if ($LASTEXITCODE -ne 0) {
        Write-Error "XeLaTeX compilation failed on pass $($currentPass). Check '$FileName.log' for details."
        exit $LASTEXITCODE
    }
}


# --- Cleanup Auxiliary Files ---
Write-Host "Cleaning up auxiliary files..."
$FilesRemoved = 0
$FilesNotFound = 0

foreach ($ext in $AuxFileExtensions) {
    $FileToDelete = "${FileName}${ext}"
    if (Test-Path -Path $FileToDelete -PathType Leaf) {
        try {
            Remove-Item -Path $FileToDelete -Force -ErrorAction Stop
            Write-Verbose "Removed: $FileToDelete"
            $FilesRemoved++
        }
        catch {
            Write-Warning "Could not remove '$FileToDelete': $($_.Exception.Message)"
        }
    }
    else {
        Write-Verbose "Not found (no need to remove): $FileToDelete"
        $FilesNotFound++
    }
}

Write-Host "----------------------------------------"
if ($LASTEXITCODE -eq 0) {
    Write-Host "XeLaTeX compilation successful for '$FileName.pdf'." -ForegroundColor Green
}
else {
    Write-Warning "XeLaTeX compilation may have encountered errors. Please check the output and '$FileName.log'."
}
Write-Host "Cleanup complete. $FilesRemoved file(s) removed. $FilesNotFound auxiliary file type(s) not found."
Write-Host "----------------------------------------"